"""empty message

Revision ID: 0d0f10469f89
Revises: df731488af83
Create Date: 2020-08-04 13:30:22.335467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0f10469f89'
down_revision = 'df731488af83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospects', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospects', sa.Column('status', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
