"""
U: drop prospects email key
D: add prospects email key

Revision ID: 1af7fceeb30c
Revises: cf23b6c2d622
Create Date: 2020-07-29 20:13:36.189462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af7fceeb30c'
down_revision = 'cf23b6c2d622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('prospects_email_key', 'prospects', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('prospects_email_key', 'prospects', ['email'])
    # ### end Alembic commands ###
