"""empty message

Revision ID: 2b3dbd60ec11
Revises: ef0105c0ae61
Create Date: 2020-08-06 17:54:06.848534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3dbd60ec11'
down_revision = 'ef0105c0ae61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credentials', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credentials')
    # ### end Alembic commands ###
