"""empty message

Revision ID: 2fae1900ba9a
Revises: 416adbd95dac
Create Date: 2020-08-04 13:55:35.336832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fae1900ba9a'
down_revision = '416adbd95dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospects', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospects', sa.Column('status', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
