"""empty message

Revision ID: 3da20d77a8ab
Revises: 2fae1900ba9a
Create Date: 2020-08-04 13:57:46.880383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da20d77a8ab'
down_revision = '2fae1900ba9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credentials')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credentials', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
