"""
U: add users credentials
D: drop users credentials

Revision ID: 416adbd95dac
Revises: edea41c24e99
Create Date: 2020-07-31 01:00:11.654695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416adbd95dac'
down_revision = 'edea41c24e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credentials', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credentials')
    # ### end Alembic commands ###
