"""empty message

Revision ID: 563f32e7d5e9
Revises: c76af553f76f
Create Date: 2020-07-24 17:48:34.834912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563f32e7d5e9'
down_revision = 'c76af553f76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstName', sa.String(length=120), nullable=False))
    op.add_column('users', sa.Column('lastName', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    # ### end Alembic commands ###
