"""
U: add users created
D: drop users created

Revision ID: c76af553f76f
Revises: ccee2f1eef5f
Create Date: 2020-07-23 20:23:19.056659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76af553f76f'
down_revision = 'ccee2f1eef5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created')
    # ### end Alembic commands ###
