"""
U: add user credentials
D: drop user credentials

Revision ID: cf23b6c2d622
Revises: 45c64dc96de5
Create Date: 2020-07-29 19:57:41.425411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf23b6c2d622'
down_revision = '45c64dc96de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credentials', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credentials')
    # ### end Alembic commands ###
