"""empty message

Revision ID: e1e2ad9b9e25
Revises: c5cb8a97feed
Create Date: 2020-07-24 11:22:19.209744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e2ad9b9e25'
down_revision = 'c5cb8a97feed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created', sa.DateTime(), server_default='1900-01-01', nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(length=50), server_default='anonymous', nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), server_default='anonymous', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'created')
    # ### end Alembic commands ###
