"""empty message

Revision ID: e5d451965daf
Revises: 416adbd95dac
Create Date: 2020-08-02 22:31:00.901826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d451965daf'
down_revision = '416adbd95dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credentials')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credentials', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
