"""empty message

Revision ID: edea41c24e99
Revises: 1af7fceeb30c
Create Date: 2020-07-31 00:58:43.442647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edea41c24e99'
down_revision = '1af7fceeb30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credentials')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credentials', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
